version: '3.5'
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass sdmastergames
    ports:
      - "6379:6379"
  receive:
    image: bull-receive
    build: ./bull-receive/
    command: yarn start
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: sdmastergames
    links:
      - redis
    ports:
      - 9090:9090
    volumes:
      - node_modules:/node_modules
  send:
    image: bull-sending
    build: ./bull-sending/
    command: yarn start
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: sdmastergames
    links:
      - redis
    ports:
      - 8080:8080
    volumes:
      - node_modules:/node_modules

volumes:
  node_modules: {}
